# Generated by Django 2.2.6 on 2019-10-31 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=100)),
                ('speciality_Chn', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'speciality',
                'verbose_name_plural': 'speciality',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('subject_Chn', models.CharField(blank=True, max_length=50)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ioms.Speciality')),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': 'subject',
            },
        ),
        migrations.CreateModel(
            name='Iom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('RFI', models.CharField(blank=True, max_length=50)),
                ('PO_Description', models.CharField(blank=True, max_length=500)),
                ('equipment', models.CharField(blank=True, max_length=1000)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('title_Chn', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('originator', models.CharField(blank=True, max_length=50)),
                ('revision', models.CharField(blank=True, max_length=10)),
                ('pdf_file', models.FileField(blank=True, upload_to='uploads/')),
                ('size', models.BigIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('document_Date', models.DateField(auto_now_add=True)),
                ('speciality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ioms.Speciality')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ioms.Subject')),
                ('updator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='修改用户', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IOM手册',
                'verbose_name_plural': 'IOM手册',
                'ordering': ('speciality',),
            },
        ),
    ]
