# Generated by Django 2.2.6 on 2019-11-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iom',
            name='PO_Description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='iom',
            name='RFI',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='iom',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='iom',
            name='document_Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='iom',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='iom',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='iom',
            name='originator',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='iom',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='iom',
            name='revision',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='iom',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='iom',
            name='title_Chn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='iom',
            name='unit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='speciality_Chn',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_Chn',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
